#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long::Descriptive;

use constant VERSION => '0.2.0';

#
# return the tarball url for the project/tag
#

sub url_for
{
    my ($whoname, $project, $tag) = @_;

    return "https://github.com/$whoname/$project/tarball/$tag";
}

# 
# reutrn download file path  
# 

sub file_for
{
    my ($whoname, $project, $tag) = @_;
    return "~/Downloads/$whoname-$project-$tag.tar.gz";
}

# 
# void download to file path  
# 

sub download_file
{
    my ($url, $file) = @_;
    `wget -q -nc -O $file $url --no-check-certificate `;
}

#
# return the checksum of specified type of data at url
#


sub checksum
{
    my ($file, $type) = @_;
    my $output = `openssl $type $file`;

    $output =~ s/^.*\(.*\)= (.*)\n$/$1/;

    return $output;
}

#
# print the checksum type for the project and tag
#

sub print_checksum
{
    my ($file, $type) = @_;
    my $checksum = checksum($file, $type);
    print "$type: $checksum\n";
}

#
# main
#

my ($opt, $usage) = describe_options(
    "Version " . VERSION . "\nusage: ghsum user/project tag",
    ['help', 'print usage information']
);

my ($whoname, $project, $tag) = @ARGV;

print($usage->text), exit if $opt->help || !$whoname || !$project || !$tag;

my $url = url_for($whoname, $project, $tag);
my $file = file_for($whoname, $project, $tag);
download_file($url, $file);

print "file: $file\n";
print_checksum($file, 'sha256');
print_checksum($file, 'rmd160');

